---
datastore: ../Data
auto_register:
    mode: EMAILS
    domains: 
        - test.com
    emails:
        - test@gmail.com
mail:
    server:
        address: smtp.gmail.com:587
        password: password
        user: test@gmail.com
    from_address: test@gmail.com
    support_address: test@gmail.com
queue:
    datastore: ../Data/queue
    max_running_jobs: 5
    loop_interval: 5
    windninja_wrapper:
        executable: /usr/bin/python
        script: windninjawrapper/windninja.py
        options: 
            - -d
